# Site settings
title: t3hsite
description: "This is project to make a reliable, maintainable and most importantly user-friendly theme for Jekyll from scratch, while learning good HTML5 and SASS/CSS."
baseurl: "/t3hsite" # the subpath of your site, e.g. /blog/
url: "http://t3hmun.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  header_offset: 1